/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as MfaVerifyRouteImport } from './routes/mfa.verify'
import { Route as MfaSetupRouteImport } from './routes/mfa.setup'
import { Route as AppTransactionHistoryRouteImport } from './routes/_app.transaction-history'
import { Route as AppPaymentTransferRouteImport } from './routes/_app.payment-transfer'
import { Route as AppMyBanksRouteImport } from './routes/_app.my-banks'
import { Route as AppHaloRouteImport } from './routes/_app.halo'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as ApiSecurityScanReportRouteImport } from './routes/api.security.scan-report'
import { Route as ApiInternalAccountsExportRouteImport } from './routes/api.internal.accounts.export'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const MfaVerifyRoute = MfaVerifyRouteImport.update({
  id: '/mfa/verify',
  path: '/mfa/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const MfaSetupRoute = MfaSetupRouteImport.update({
  id: '/mfa/setup',
  path: '/mfa/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTransactionHistoryRoute = AppTransactionHistoryRouteImport.update({
  id: '/transaction-history',
  path: '/transaction-history',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentTransferRoute = AppPaymentTransferRouteImport.update({
  id: '/payment-transfer',
  path: '/payment-transfer',
  getParentRoute: () => AppRoute,
} as any)
const AppMyBanksRoute = AppMyBanksRouteImport.update({
  id: '/my-banks',
  path: '/my-banks',
  getParentRoute: () => AppRoute,
} as any)
const AppHaloRoute = AppHaloRouteImport.update({
  id: '/halo',
  path: '/halo',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const ApiSecurityScanReportRoute = ApiSecurityScanReportRouteImport.update({
  id: '/api/security/scan-report',
  path: '/api/security/scan-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalAccountsExportRoute =
  ApiInternalAccountsExportRouteImport.update({
    id: '/api/internal/accounts/export',
    path: '/api/internal/accounts/export',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/security': typeof SecurityRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/admin': typeof AppAdminRoute
  '/halo': typeof AppHaloRoute
  '/my-banks': typeof AppMyBanksRoute
  '/payment-transfer': typeof AppPaymentTransferRoute
  '/transaction-history': typeof AppTransactionHistoryRoute
  '/mfa/setup': typeof MfaSetupRoute
  '/mfa/verify': typeof MfaVerifyRoute
  '/api/security/scan-report': typeof ApiSecurityScanReportRoute
  '/api/internal/accounts/export': typeof ApiInternalAccountsExportRoute
}
export interface FileRoutesByTo {
  '/security': typeof SecurityRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/admin': typeof AppAdminRoute
  '/halo': typeof AppHaloRoute
  '/my-banks': typeof AppMyBanksRoute
  '/payment-transfer': typeof AppPaymentTransferRoute
  '/transaction-history': typeof AppTransactionHistoryRoute
  '/mfa/setup': typeof MfaSetupRoute
  '/mfa/verify': typeof MfaVerifyRoute
  '/': typeof AppIndexRoute
  '/api/security/scan-report': typeof ApiSecurityScanReportRoute
  '/api/internal/accounts/export': typeof ApiInternalAccountsExportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/security': typeof SecurityRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/halo': typeof AppHaloRoute
  '/_app/my-banks': typeof AppMyBanksRoute
  '/_app/payment-transfer': typeof AppPaymentTransferRoute
  '/_app/transaction-history': typeof AppTransactionHistoryRoute
  '/mfa/setup': typeof MfaSetupRoute
  '/mfa/verify': typeof MfaVerifyRoute
  '/_app/': typeof AppIndexRoute
  '/api/security/scan-report': typeof ApiSecurityScanReportRoute
  '/api/internal/accounts/export': typeof ApiInternalAccountsExportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/security'
    | '/sign-in'
    | '/sign-up'
    | '/admin'
    | '/halo'
    | '/my-banks'
    | '/payment-transfer'
    | '/transaction-history'
    | '/mfa/setup'
    | '/mfa/verify'
    | '/api/security/scan-report'
    | '/api/internal/accounts/export'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/security'
    | '/sign-in'
    | '/sign-up'
    | '/admin'
    | '/halo'
    | '/my-banks'
    | '/payment-transfer'
    | '/transaction-history'
    | '/mfa/setup'
    | '/mfa/verify'
    | '/'
    | '/api/security/scan-report'
    | '/api/internal/accounts/export'
  id:
    | '__root__'
    | '/_app'
    | '/security'
    | '/sign-in'
    | '/sign-up'
    | '/_app/admin'
    | '/_app/halo'
    | '/_app/my-banks'
    | '/_app/payment-transfer'
    | '/_app/transaction-history'
    | '/mfa/setup'
    | '/mfa/verify'
    | '/_app/'
    | '/api/security/scan-report'
    | '/api/internal/accounts/export'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SecurityRoute: typeof SecurityRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  MfaSetupRoute: typeof MfaSetupRoute
  MfaVerifyRoute: typeof MfaVerifyRoute
  ApiSecurityScanReportRoute: typeof ApiSecurityScanReportRoute
  ApiInternalAccountsExportRoute: typeof ApiInternalAccountsExportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/mfa/verify': {
      id: '/mfa/verify'
      path: '/mfa/verify'
      fullPath: '/mfa/verify'
      preLoaderRoute: typeof MfaVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfa/setup': {
      id: '/mfa/setup'
      path: '/mfa/setup'
      fullPath: '/mfa/setup'
      preLoaderRoute: typeof MfaSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/transaction-history': {
      id: '/_app/transaction-history'
      path: '/transaction-history'
      fullPath: '/transaction-history'
      preLoaderRoute: typeof AppTransactionHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payment-transfer': {
      id: '/_app/payment-transfer'
      path: '/payment-transfer'
      fullPath: '/payment-transfer'
      preLoaderRoute: typeof AppPaymentTransferRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-banks': {
      id: '/_app/my-banks'
      path: '/my-banks'
      fullPath: '/my-banks'
      preLoaderRoute: typeof AppMyBanksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/halo': {
      id: '/_app/halo'
      path: '/halo'
      fullPath: '/halo'
      preLoaderRoute: typeof AppHaloRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/security/scan-report': {
      id: '/api/security/scan-report'
      path: '/api/security/scan-report'
      fullPath: '/api/security/scan-report'
      preLoaderRoute: typeof ApiSecurityScanReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/accounts/export': {
      id: '/api/internal/accounts/export'
      path: '/api/internal/accounts/export'
      fullPath: '/api/internal/accounts/export'
      preLoaderRoute: typeof ApiInternalAccountsExportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppHaloRoute: typeof AppHaloRoute
  AppMyBanksRoute: typeof AppMyBanksRoute
  AppPaymentTransferRoute: typeof AppPaymentTransferRoute
  AppTransactionHistoryRoute: typeof AppTransactionHistoryRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppHaloRoute: AppHaloRoute,
  AppMyBanksRoute: AppMyBanksRoute,
  AppPaymentTransferRoute: AppPaymentTransferRoute,
  AppTransactionHistoryRoute: AppTransactionHistoryRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SecurityRoute: SecurityRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  MfaSetupRoute: MfaSetupRoute,
  MfaVerifyRoute: MfaVerifyRoute,
  ApiSecurityScanReportRoute: ApiSecurityScanReportRoute,
  ApiInternalAccountsExportRoute: ApiInternalAccountsExportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
